[package]
name = "effnes-cpu"
version = "0.1.0"
edition = "2024"

[dependencies]
bitflags = "2.11.0"
effnes-bus = { path = "../effnes-bus" }

[dev-dependencies]
effnes-ca-cpu = { path = "../effnes-ca-cpu" }
effnes-basic-cpu = { path = "../effnes-basic-cpu" }
